### ISSUE TITLE
Tratamento de resposta / Maiúsculas e Minúsculas

### ISSUE THREAD

**Issue by luisangelorjr** [vnssnscto/pythonfiles#1]
Opa!
Conforme vemos na imagem, ele ainda não consegue tratar maiúsculas e minúsculas:

![image](https://user-images.githubusercontent.com/22268900/156800400-5debb2a6-6826-4c3a-b8b2-72a18d8cd66b.png)

**Comment by vnssnscto** [comment]
Oi, Luis!

Obrigada pela observação, segue código atualizado e funcionando conforme print:


![image](https://user-images.githubusercontent.com/94928648/157262263-ef6e6c2a-6d59-44fa-9d2c-7ba3babf2692.png)
